2014/09/06 06:21:58 [error] [exception.CException] exception 'CException' with message 'Alias "booster.widgets.TbButton" is invalid. Make sure it points to an existing directory or file.' in E:\Yii\framework\YiiBase.php:347
Stack trace:
#0 E:\Yii\framework\web\CWidgetFactory.php(146): YiiBase::import('booster.widgets...', true)
#1 E:\Yii\framework\web\CBaseController.php(146): CWidgetFactory->createWidget(Object(SiteController), 'booster.widgets...', Array)
#2 E:\Yii\framework\web\CBaseController.php(172): CBaseController->createWidget('booster.widgets...', Array)
#3 E:\xampp\htdocs\Testapp\protected\views\site\index.php(27): CBaseController->widget('booster.widgets...', Array)
#4 E:\Yii\framework\web\CBaseController.php(126): require('E:\\xampp\\htdocs...')
#5 E:\Yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('E:\\xampp\\htdocs...', NULL, true)
#6 E:\Yii\framework\web\CController.php(869): CBaseController->renderFile('E:\\xampp\\htdocs...', NULL, true)
#7 E:\Yii\framework\web\CController.php(782): CController->renderPartial('index', NULL, true)
#8 E:\xampp\htdocs\Testapp\protected\controllers\SiteController.php(32): CController->render('index')
#9 E:\Yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#10 E:\Yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 E:\Yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#12 E:\Yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 E:\Yii\framework\web\CWebApplication.php(282): CController->run('')
#14 E:\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#15 E:\Yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#16 E:\xampp\htdocs\Testapp\index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/Testapp/
---
2014/09/06 19:14:19 [error] [exception.CException] exception 'CException' with message 'Property "User.email" is not defined.' in E:\Yii\framework\base\CComponent.php:130
Stack trace:
#0 E:\Yii\framework\db\ar\CActiveRecord.php(145): CComponent->__get('email')
#1 E:\Yii\framework\web\helpers\CHtml.php(2529): CActiveRecord->__get('email')
#2 E:\Yii\framework\web\helpers\CHtml.php(2252): CHtml::resolveValue(Object(User), 'email')
#3 E:\Yii\framework\web\helpers\CHtml.php(1434): CHtml::activeInputField('text', Object(User), 'email', Array)
#4 E:\Yii\framework\web\widgets\CActiveForm.php(725): CHtml::activeTextField(Object(User), 'email', Array)
#5 E:\xampp\htdocs\Testapp\protected\views\user\_form.php(36): CActiveForm->textField(Object(User), 'email', Array)
#6 E:\Yii\framework\web\CBaseController.php(126): require('E:\\xampp\\htdocs...')
#7 E:\Yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('E:\\xampp\\htdocs...', Array, true)
#8 E:\Yii\framework\web\CController.php(869): CBaseController->renderFile('E:\\xampp\\htdocs...', Array, true)
#9 E:\xampp\htdocs\Testapp\protected\views\user\create.php(18): CController->renderPartial('_form', Array)
#10 E:\Yii\framework\web\CBaseController.php(126): require('E:\\xampp\\htdocs...')
#11 E:\Yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('E:\\xampp\\htdocs...', Array, true)
#12 E:\Yii\framework\web\CController.php(869): CBaseController->renderFile('E:\\xampp\\htdocs...', Array, true)
#13 E:\Yii\framework\web\CController.php(782): CController->renderPartial('create', Array, true)
#14 E:\xampp\htdocs\Testapp\protected\controllers\UserController.php(79): CController->render('create', Array)
#15 E:\Yii\framework\web\actions\CInlineAction.php(49): UserController->actionCreate()
#16 E:\Yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#17 E:\Yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#18 E:\Yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#19 E:\Yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#20 E:\Yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#21 E:\Yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#22 E:\Yii\framework\web\CController.php(291): CFilterChain->run()
#23 E:\Yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#24 E:\Yii\framework\web\CWebApplication.php(282): CController->run('create')
#25 E:\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/create')
#26 E:\Yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#27 E:\xampp\htdocs\Testapp\index.php(13): CApplication->run()
#28 {main}
REQUEST_URI=/Testapp/index.php?r=user/create
HTTP_REFERER=http://localhost/Testapp/index.php?r=site/index
---
2014/09/06 19:15:37 [error] [php] include(bCrypt.php): failed to open stream: No such file or directory (E:\Yii\framework\YiiBase.php:427)
Stack trace:
#0 E:\xampp\htdocs\Testapp\protected\models\User.php(107): spl_autoload_call()
#1 E:\xampp\htdocs\Testapp\protected\models\User.php(101): User->encrypt()
#2 E:\Yii\framework\base\CModel.php(160): User->afterValidate()
#3 E:\Yii\framework\db\ar\CActiveRecord.php(805): User->validate()
#4 E:\xampp\htdocs\Testapp\protected\controllers\UserController.php(73): User->save()
#5 E:\Yii\framework\web\actions\CInlineAction.php(49): UserController->actionCreate()
#6 E:\Yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#7 E:\Yii\framework\web\filters\CFilterChain.php(133): UserController->runAction()
#8 E:\Yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#9 E:\Yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#10 E:\Yii\framework\web\filters\CInlineFilter.php(58): UserController->filterAccessControl()
#11 E:\Yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#12 E:\Yii\framework\web\CController.php(291): CFilterChain->run()
#13 E:\Yii\framework\web\CController.php(265): UserController->runActionWithFilters()
#14 E:\Yii\framework\web\CWebApplication.php(282): UserController->run()
#15 E:\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#16 E:\Yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#17 E:\xampp\htdocs\Testapp\index.php(13): CWebApplication->run()
REQUEST_URI=/Testapp/index.php?r=user/create
in E:\xampp\htdocs\Testapp\protected\models\User.php (107)
in E:\xampp\htdocs\Testapp\protected\models\User.php (101)
in E:\xampp\htdocs\Testapp\protected\controllers\UserController.php (73)
2014/09/06 19:41:20 [error] [exception.CException] exception 'CException' with message 'Property "UserIdentity._id" is not defined.' in E:\Yii\framework\base\CComponent.php:130
Stack trace:
#0 E:\xampp\htdocs\Testapp\protected\components\UserIdentity.php(37): CComponent->__get('_id')
#1 E:\Yii\framework\web\auth\CWebUser.php(229): UserIdentity->getId()
#2 E:\xampp\htdocs\Testapp\protected\models\LoginForm.php(71): CWebUser->login(Object(UserIdentity), 0)
#3 E:\xampp\htdocs\Testapp\protected\controllers\SiteController.php(94): LoginForm->login()
#4 E:\Yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#5 E:\Yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#6 E:\Yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#7 E:\Yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 E:\Yii\framework\web\CWebApplication.php(282): CController->run('login')
#9 E:\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#10 E:\Yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#11 E:\xampp\htdocs\Testapp\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/Testapp/index.php?r=site/login
HTTP_REFERER=http://localhost/Testapp/index.php?r=site/login
---
2014/09/06 19:44:02 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in E:\Yii\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 E:\Yii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 E:\Yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 E:\Yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 E:\Yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 E:\Yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 E:\Yii\framework\web\CController.php(291): CFilterChain->run()
#6 E:\Yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 E:\Yii\framework\web\CWebApplication.php(282): CController->run('view')
#8 E:\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/view')
#9 E:\Yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 E:\xampp\htdocs\Testapp\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/Testapp/index.php?r=user/view&id=4
HTTP_REFERER=http://localhost/Testapp/index.php?r=site/login
---
2014/09/06 20:58:45 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "controller/action".' in E:\Yii\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('controller/acti...')
#1 E:\Yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 E:\xampp\htdocs\Testapp\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/Testapp/index.php?r=controller/action
HTTP_REFERER=http://localhost/Testapp/index.php
---
2014/09/07 00:58:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "controller/action".' in E:\Yii\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('controller/acti...')
#1 E:\Yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 E:\xampp\htdocs\Testapp\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/Testapp/index.php?r=controller/action
HTTP_REFERER=http://localhost/Testapp/index.php?r=site/index
---
2014/09/07 00:58:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "controller/action".' in E:\Yii\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('controller/acti...')
#1 E:\Yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 E:\xampp\htdocs\Testapp\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/Testapp/index.php?r=controller/action
HTTP_REFERER=http://localhost/Testapp/index.php?r=site/index
---
2014/09/07 01:02:24 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "QuestionController/actionNext(true)".' in E:\Yii\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('QuestionControl...')
#1 E:\Yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 E:\xampp\htdocs\Testapp\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/Testapp/index.php?r=QuestionController/actionNext(true)
HTTP_REFERER=http://localhost/Testapp/index.php?r=site/index
---
2014/09/07 01:03:28 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "QuestionController/actionNext".' in E:\Yii\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('QuestionControl...')
#1 E:\Yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 E:\xampp\htdocs\Testapp\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/Testapp/index.php?r=QuestionController/actionNext
HTTP_REFERER=http://localhost/Testapp/index.php?r=site/index
---
2014/09/07 01:03:59 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "QuestionController/Next".' in E:\Yii\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('QuestionControl...')
#1 E:\Yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 E:\xampp\htdocs\Testapp\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/Testapp/index.php?r=QuestionController/Next
HTTP_REFERER=http://localhost/Testapp/index.php?r=site/index
---
2014/09/07 01:04:01 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "QuestionController/Next".' in E:\Yii\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('QuestionControl...')
#1 E:\Yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 E:\xampp\htdocs\Testapp\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/Testapp/index.php?r=QuestionController/Next
HTTP_REFERER=http://localhost/Testapp/index.php?r=site/index
---
2014/09/07 01:04:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "controller/action".' in E:\Yii\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('controller/acti...')
#1 E:\Yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 E:\xampp\htdocs\Testapp\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/Testapp/index.php?r=controller/action
HTTP_REFERER=http://localhost/Testapp/index.php?r=site/index
---
2014/09/07 01:04:11 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "QuestionController/Next".' in E:\Yii\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('QuestionControl...')
#1 E:\Yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 E:\xampp\htdocs\Testapp\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/Testapp/index.php?r=QuestionController/Next
HTTP_REFERER=http://localhost/Testapp/index.php?r=site/index
---
2014/09/07 01:09:50 [error] [php] Undefined variable: question (E:\xampp\htdocs\Testapp\protected\controllers\QuestionController.php:13)
Stack trace:
#0 E:\Yii\framework\web\CController.php(286): QuestionController->runAction()
#1 E:\Yii\framework\web\CController.php(265): QuestionController->runActionWithFilters()
#2 E:\Yii\framework\web\CWebApplication.php(282): QuestionController->run()
#3 E:\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 E:\Yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#5 E:\xampp\htdocs\Testapp\index.php(13): CWebApplication->run()
REQUEST_URI=/Testapp/index.php?r=Question/Next
in E:\xampp\htdocs\Testapp\protected\controllers\QuestionController.php (13)
in E:\xampp\htdocs\Testapp\index.php (13)
2014/09/07 01:10:18 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[HY093]: Invalid parameter number: no parameters were bound. The SQL statement executed was: CALL randomQuestion(:user, :question).
in E:\xampp\htdocs\Testapp\protected\controllers\QuestionController.php (14)
in E:\xampp\htdocs\Testapp\index.php (13)
2014/09/07 01:10:18 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[HY093]: Invalid parameter number: no parameters were bound. The SQL statement executed was: CALL randomQuestion(:user, :question)' in E:\Yii\framework\db\CDbCommand.php:543
Stack trace:
#0 E:\Yii\framework\db\CDbCommand.php(396): CDbCommand->queryInternal('fetchAll', Array, Array)
#1 E:\xampp\htdocs\Testapp\protected\controllers\QuestionController.php(14): CDbCommand->queryAll(Array)
#2 E:\Yii\framework\web\actions\CInlineAction.php(49): QuestionController->actionNext()
#3 E:\Yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 E:\Yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 E:\Yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 E:\Yii\framework\web\CWebApplication.php(282): CController->run('Next')
#7 E:\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('Question/Next')
#8 E:\Yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#9 E:\xampp\htdocs\Testapp\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/Testapp/index.php?r=Question/Next
HTTP_REFERER=http://localhost/Testapp/index.php?r=site/index
---
2014/09/07 01:15:24 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ' @out)' at line 1. The SQL statement executed was: CALL randomQuestion(, @out).
in E:\xampp\htdocs\Testapp\protected\controllers\QuestionController.php (15)
in E:\xampp\htdocs\Testapp\index.php (13)
2014/09/07 01:15:24 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ' @out)' at line 1. The SQL statement executed was: CALL randomQuestion(, @out)' in E:\Yii\framework\db\CDbCommand.php:358
Stack trace:
#0 E:\xampp\htdocs\Testapp\protected\controllers\QuestionController.php(15): CDbCommand->execute()
#1 E:\Yii\framework\web\actions\CInlineAction.php(49): QuestionController->actionNext()
#2 E:\Yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#3 E:\Yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#4 E:\Yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 E:\Yii\framework\web\CWebApplication.php(282): CController->run('Next')
#6 E:\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('Question/Next')
#7 E:\Yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#8 E:\xampp\htdocs\Testapp\index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/Testapp/index.php?r=Question/Next
HTTP_REFERER=http://localhost/Testapp/index.php?r=site/index
---
2014/09/07 01:17:08 [error] [php] Undefined variable: Yii (E:\xampp\htdocs\Testapp\protected\controllers\QuestionController.php:14)
Stack trace:
#0 E:\Yii\framework\web\CController.php(286): QuestionController->runAction()
#1 E:\Yii\framework\web\CController.php(265): QuestionController->runActionWithFilters()
#2 E:\Yii\framework\web\CWebApplication.php(282): QuestionController->run()
#3 E:\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 E:\Yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#5 E:\xampp\htdocs\Testapp\index.php(13): CWebApplication->run()
REQUEST_URI=/Testapp/index.php?r=Question/Next
in E:\xampp\htdocs\Testapp\protected\controllers\QuestionController.php (14)
in E:\xampp\htdocs\Testapp\index.php (13)
2014/09/07 01:17:49 [error] [php] Trying to get property of non-object (E:\xampp\htdocs\Testapp\protected\controllers\QuestionController.php:18)
Stack trace:
#0 E:\Yii\framework\web\CController.php(286): QuestionController->runAction()
#1 E:\Yii\framework\web\CController.php(265): QuestionController->runActionWithFilters()
#2 E:\Yii\framework\web\CWebApplication.php(282): QuestionController->run()
#3 E:\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 E:\Yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#5 E:\xampp\htdocs\Testapp\index.php(13): CWebApplication->run()
REQUEST_URI=/Testapp/index.php?r=Question/Next
in E:\xampp\htdocs\Testapp\protected\controllers\QuestionController.php (18)
in E:\xampp\htdocs\Testapp\index.php (13)
2014/09/07 01:33:26 [error] [exception.CException] exception 'CException' with message 'Property "CDbCommand.question" is not defined.' in E:\Yii\framework\base\CComponent.php:130
Stack trace:
#0 E:\xampp\htdocs\Testapp\protected\controllers\QuestionController.php(18): CComponent->__get('question')
#1 E:\Yii\framework\web\actions\CInlineAction.php(49): QuestionController->actionNext()
#2 E:\Yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#3 E:\Yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#4 E:\Yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 E:\Yii\framework\web\CWebApplication.php(282): CController->run('Next')
#6 E:\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('Question/Next')
#7 E:\Yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#8 E:\xampp\htdocs\Testapp\index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/Testapp/index.php?r=Question/Next
HTTP_REFERER=http://localhost/Testapp/index.php?r=site/index
---
2014/09/07 01:33:52 [error] [php] Trying to get property of non-object (E:\xampp\htdocs\Testapp\protected\controllers\QuestionController.php:18)
Stack trace:
#0 E:\Yii\framework\web\CController.php(286): QuestionController->runAction()
#1 E:\Yii\framework\web\CController.php(265): QuestionController->runActionWithFilters()
#2 E:\Yii\framework\web\CWebApplication.php(282): QuestionController->run()
#3 E:\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 E:\Yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#5 E:\xampp\htdocs\Testapp\index.php(13): CWebApplication->run()
REQUEST_URI=/Testapp/index.php?r=Question/Next
in E:\xampp\htdocs\Testapp\protected\controllers\QuestionController.php (18)
in E:\xampp\htdocs\Testapp\index.php (13)
2014/09/07 01:34:59 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "controller/action".' in E:\Yii\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('controller/acti...')
#1 E:\Yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 E:\xampp\htdocs\Testapp\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/Testapp/index.php?r=controller/action
HTTP_REFERER=http://localhost/Testapp/index.php?r=site/index
---
2014/09/07 01:35:04 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "controller/action".' in E:\Yii\framework\web\CWebApplication.php:286
Stack trace:
#0 E:\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('controller/acti...')
#1 E:\Yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 E:\xampp\htdocs\Testapp\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/Testapp/index.php?r=controller/action
HTTP_REFERER=http://localhost/Testapp/index.php?r=site/index
---
2014/09/07 02:11:10 [error] [exception.CException] exception 'CException' with message 'SiteController cannot find the requested view "Site/index".' in E:\Yii\framework\web\CController.php:878
Stack trace:
#0 E:\Yii\framework\web\CController.php(782): CController->renderPartial('Site/index', Array, true)
#1 E:\xampp\htdocs\Testapp\protected\controllers\SiteController.php(45): CController->render('Site/index', Array)
#2 E:\xampp\htdocs\Testapp\protected\controllers\SiteController.php(32): SiteController->actionNext()
#3 E:\Yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#4 E:\Yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 E:\Yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#6 E:\Yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 E:\Yii\framework\web\CWebApplication.php(282): CController->run('')
#8 E:\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#9 E:\Yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 E:\xampp\htdocs\Testapp\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/Testapp/
---
2014/09/07 02:12:49 [error] [exception.CException] exception 'CException' with message 'QuestionController cannot find the requested view "Site/index".' in E:\Yii\framework\web\CController.php:878
Stack trace:
#0 E:\Yii\framework\web\CController.php(782): CController->renderPartial('Site/index', Array, true)
#1 E:\xampp\htdocs\Testapp\protected\controllers\QuestionController.php(20): CController->render('Site/index', Array)
#2 E:\Yii\framework\web\actions\CInlineAction.php(49): QuestionController->actionNext()
#3 E:\Yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 E:\Yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 E:\Yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 E:\Yii\framework\web\CWebApplication.php(282): CController->run('Next')
#7 E:\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('Question/Next')
#8 E:\Yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#9 E:\xampp\htdocs\Testapp\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/Testapp/index.php?r=Question/Next
HTTP_REFERER=http://localhost/Testapp/index.php?r=site/index
---
2014/09/07 02:14:38 [error] [exception.CException] exception 'CException' with message 'QuestionController cannot find the requested view "Site/index".' in E:\Yii\framework\web\CController.php:878
Stack trace:
#0 E:\Yii\framework\web\CController.php(782): CController->renderPartial('Site/index', Array, true)
#1 E:\xampp\htdocs\Testapp\protected\controllers\QuestionController.php(20): CController->render('Site/index', Array)
#2 E:\Yii\framework\web\actions\CInlineAction.php(49): QuestionController->actionNext()
#3 E:\Yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 E:\Yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 E:\Yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 E:\Yii\framework\web\CWebApplication.php(282): CController->run('Next')
#7 E:\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('Question/Next')
#8 E:\Yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#9 E:\xampp\htdocs\Testapp\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/Testapp/index.php?r=Question/Next
HTTP_REFERER=http://localhost/Testapp/index.php?r=site/index
---
2014/09/07 02:22:11 [error] [php] Undefined variable: connection (E:\xampp\htdocs\Testapp\protected\controllers\SiteController.php:54)
Stack trace:
#0 E:\Yii\framework\web\CController.php(286): SiteController->runAction()
#1 E:\Yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#2 E:\Yii\framework\web\CWebApplication.php(282): SiteController->run()
#3 E:\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 E:\Yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#5 E:\xampp\htdocs\Testapp\index.php(13): CWebApplication->run()
REQUEST_URI=/Testapp/index.php?r=Site/Correct
in E:\xampp\htdocs\Testapp\protected\controllers\SiteController.php (54)
in E:\xampp\htdocs\Testapp\index.php (13)
2014/09/07 02:22:28 [error] [php] Undefined variable: connection (E:\xampp\htdocs\Testapp\protected\controllers\SiteController.php:54)
Stack trace:
#0 E:\Yii\framework\web\CController.php(286): SiteController->runAction()
#1 E:\Yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#2 E:\Yii\framework\web\CWebApplication.php(282): SiteController->run()
#3 E:\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 E:\Yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#5 E:\xampp\htdocs\Testapp\index.php(13): CWebApplication->run()
REQUEST_URI=/Testapp/index.php?r=Site/Correct
in E:\xampp\htdocs\Testapp\protected\controllers\SiteController.php (54)
in E:\xampp\htdocs\Testapp\index.php (13)
2014/09/07 02:25:57 [error] [php] Undefined variable: questionID (E:\xampp\htdocs\Testapp\protected\controllers\SiteController.php:59)
Stack trace:
#0 E:\Yii\framework\web\CController.php(286): SiteController->runAction()
#1 E:\Yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#2 E:\Yii\framework\web\CWebApplication.php(282): SiteController->run()
#3 E:\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 E:\Yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#5 E:\xampp\htdocs\Testapp\index.php(13): CWebApplication->run()
REQUEST_URI=/Testapp/index.php?r=Site/Correct
in E:\xampp\htdocs\Testapp\protected\controllers\SiteController.php (59)
in E:\xampp\htdocs\Testapp\index.php (13)
2014/09/07 02:32:46 [error] [php] Illegal offset type in isset or empty (E:\Yii\framework\validators\CValidator.php:247)
Stack trace:
#0 E:\Yii\framework\db\ar\CActiveRecord.php(805): Correct->validate()
#1 E:\xampp\htdocs\Testapp\protected\controllers\SiteController.php(62): Correct->save()
#2 E:\Yii\framework\web\actions\CInlineAction.php(49): SiteController->actionCorrect()
#3 E:\Yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#4 E:\Yii\framework\web\CController.php(286): SiteController->runAction()
#5 E:\Yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#6 E:\Yii\framework\web\CWebApplication.php(282): SiteController->run()
#7 E:\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#8 E:\Yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#9 E:\xampp\htdocs\Testapp\index.php(13): CWebApplication->run()
REQUEST_URI=/Testapp/index.php?r=Site/Correct
in E:\xampp\htdocs\Testapp\protected\controllers\SiteController.php (62)
in E:\xampp\htdocs\Testapp\index.php (13)
2014/09/07 02:41:41 [error] [php] Illegal offset type in isset or empty (E:\Yii\framework\validators\CValidator.php:247)
Stack trace:
#0 E:\Yii\framework\db\ar\CActiveRecord.php(805): Correct->validate()
#1 E:\xampp\htdocs\Testapp\protected\controllers\SiteController.php(58): Correct->save()
#2 E:\Yii\framework\web\actions\CInlineAction.php(49): SiteController->actionCorrect()
#3 E:\Yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#4 E:\Yii\framework\web\CController.php(286): SiteController->runAction()
#5 E:\Yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#6 E:\Yii\framework\web\CWebApplication.php(282): SiteController->run()
#7 E:\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#8 E:\Yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#9 E:\xampp\htdocs\Testapp\index.php(13): CWebApplication->run()
REQUEST_URI=/Testapp/index.php?r=Site/Correct
in E:\xampp\htdocs\Testapp\protected\controllers\SiteController.php (58)
in E:\xampp\htdocs\Testapp\index.php (13)
2014/09/07 02:50:36 [error] [php] Illegal offset type in isset or empty (E:\Yii\framework\validators\CValidator.php:247)
Stack trace:
#0 E:\Yii\framework\db\ar\CActiveRecord.php(805): Correct->validate()
#1 E:\xampp\htdocs\Testapp\protected\controllers\SiteController.php(58): Correct->save()
#2 E:\Yii\framework\web\actions\CInlineAction.php(49): SiteController->actionCorrect()
#3 E:\Yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#4 E:\Yii\framework\web\CController.php(286): SiteController->runAction()
#5 E:\Yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#6 E:\Yii\framework\web\CWebApplication.php(282): SiteController->run()
#7 E:\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#8 E:\Yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#9 E:\xampp\htdocs\Testapp\index.php(13): CWebApplication->run()
REQUEST_URI=/Testapp/index.php?r=Site/Correct
in E:\xampp\htdocs\Testapp\protected\controllers\SiteController.php (58)
in E:\xampp\htdocs\Testapp\index.php (13)
2014/09/07 02:52:12 [error] [php] Illegal offset type in isset or empty (E:\Yii\framework\validators\CValidator.php:247)
Stack trace:
#0 E:\Yii\framework\db\ar\CActiveRecord.php(805): Correct->validate()
#1 E:\xampp\htdocs\Testapp\protected\controllers\SiteController.php(58): Correct->save()
#2 E:\Yii\framework\web\actions\CInlineAction.php(49): SiteController->actionCorrect()
#3 E:\Yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#4 E:\Yii\framework\web\CController.php(286): SiteController->runAction()
#5 E:\Yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#6 E:\Yii\framework\web\CWebApplication.php(282): SiteController->run()
#7 E:\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#8 E:\Yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#9 E:\xampp\htdocs\Testapp\index.php(13): CWebApplication->run()
REQUEST_URI=/Testapp/index.php?r=Site/Correct
in E:\xampp\htdocs\Testapp\protected\controllers\SiteController.php (58)
in E:\xampp\htdocs\Testapp\index.php (13)
2014/09/07 03:05:08 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'userID' cannot be null. The SQL statement executed was: INSERT INTO correct (userID, questionID) VALUES (:user_id, :question_id).
in E:\xampp\htdocs\Testapp\protected\controllers\SiteController.php (63)
in E:\xampp\htdocs\Testapp\index.php (13)
2014/09/07 03:05:08 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'userID' cannot be null. The SQL statement executed was: INSERT INTO correct (userID, questionID) VALUES (:user_id, :question_id)' in E:\Yii\framework\db\CDbCommand.php:358
Stack trace:
#0 E:\xampp\htdocs\Testapp\protected\controllers\SiteController.php(63): CDbCommand->execute(Array)
#1 E:\Yii\framework\web\actions\CInlineAction.php(49): SiteController->actionCorrect()
#2 E:\Yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#3 E:\Yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#4 E:\Yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 E:\Yii\framework\web\CWebApplication.php(282): CController->run('Correct')
#6 E:\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('Site/Correct')
#7 E:\Yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#8 E:\xampp\htdocs\Testapp\index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/Testapp/index.php?r=Site/Correct
HTTP_REFERER=http://localhost/Testapp/index.php?r=site/index
---
2014/09/07 03:14:28 [error] [exception.CException] exception 'CException' with message 'Property "CWebUser.user_id" is not defined.' in E:\Yii\framework\base\CComponent.php:130
Stack trace:
#0 E:\Yii\framework\web\auth\CWebUser.php(146): CComponent->__get('user_id')
#1 E:\xampp\htdocs\Testapp\protected\controllers\SiteController.php(66): CWebUser->__get('user_id')
#2 E:\Yii\framework\web\actions\CInlineAction.php(49): SiteController->actionCorrect()
#3 E:\Yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 E:\Yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 E:\Yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 E:\Yii\framework\web\CWebApplication.php(282): CController->run('Correct')
#7 E:\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('Site/Correct')
#8 E:\Yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#9 E:\xampp\htdocs\Testapp\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/Testapp/index.php?r=Site/Correct
HTTP_REFERER=http://localhost/Testapp/
---
2014/09/07 03:30:49 [error] [exception.CException] exception 'CException' with message 'Property "CWebUser.userID" is not defined.' in E:\Yii\framework\base\CComponent.php:130
Stack trace:
#0 E:\Yii\framework\web\auth\CWebUser.php(146): CComponent->__get('userID')
#1 E:\xampp\htdocs\Testapp\protected\controllers\SiteController.php(66): CWebUser->__get('userID')
#2 E:\Yii\framework\web\actions\CInlineAction.php(49): SiteController->actionCorrect()
#3 E:\Yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 E:\Yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 E:\Yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 E:\Yii\framework\web\CWebApplication.php(282): CController->run('Correct')
#7 E:\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('Site/Correct')
#8 E:\Yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#9 E:\xampp\htdocs\Testapp\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/Testapp/index.php?r=Site/Correct
HTTP_REFERER=http://localhost/Testapp/
---
2014/09/07 03:35:31 [error] [php] Trying to get property of non-object (E:\xampp\htdocs\Testapp\protected\views\site\index.php:9)
Stack trace:
#0 E:\Yii\framework\web\CController.php(869): SiteController->renderFile()
#1 E:\Yii\framework\web\CController.php(782): SiteController->renderPartial()
#2 E:\xampp\htdocs\Testapp\protected\controllers\SiteController.php(47): SiteController->render()
#3 E:\xampp\htdocs\Testapp\protected\controllers\SiteController.php(69): SiteController->actionNext()
#4 E:\Yii\framework\web\actions\CInlineAction.php(49): SiteController->actionCorrect()
#5 E:\Yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#6 E:\Yii\framework\web\CController.php(286): SiteController->runAction()
#7 E:\Yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#8 E:\Yii\framework\web\CWebApplication.php(282): SiteController->run()
#9 E:\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#10 E:\Yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#11 E:\xampp\htdocs\Testapp\index.php(13): CWebApplication->run()
REQUEST_URI=/Testapp/index.php?r=Site/Correct
in E:\xampp\htdocs\Testapp\protected\views\site\index.php (9)
in E:\xampp\htdocs\Testapp\protected\controllers\SiteController.php (47)
in E:\xampp\htdocs\Testapp\protected\controllers\SiteController.php (69)
2014/09/07 03:37:24 [error] [php] Trying to get property of non-object (E:\xampp\htdocs\Testapp\protected\views\site\index.php:12)
Stack trace:
#0 E:\Yii\framework\web\CController.php(869): SiteController->renderFile()
#1 E:\Yii\framework\web\CController.php(782): SiteController->renderPartial()
#2 E:\xampp\htdocs\Testapp\protected\controllers\SiteController.php(47): SiteController->render()
#3 E:\xampp\htdocs\Testapp\protected\controllers\SiteController.php(69): SiteController->actionNext()
#4 E:\Yii\framework\web\actions\CInlineAction.php(49): SiteController->actionCorrect()
#5 E:\Yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#6 E:\Yii\framework\web\CController.php(286): SiteController->runAction()
#7 E:\Yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#8 E:\Yii\framework\web\CWebApplication.php(282): SiteController->run()
#9 E:\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#10 E:\Yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#11 E:\xampp\htdocs\Testapp\index.php(13): CWebApplication->run()
REQUEST_URI=/Testapp/index.php?r=Site/Correct
in E:\xampp\htdocs\Testapp\protected\views\site\index.php (12)
in E:\xampp\htdocs\Testapp\protected\controllers\SiteController.php (47)
in E:\xampp\htdocs\Testapp\protected\controllers\SiteController.php (69)
2014/09/07 03:45:52 [error] [php] Undefined variable: question (E:\xampp\htdocs\Testapp\protected\controllers\SiteController.php:79)
Stack trace:
#0 E:\Yii\framework\web\CController.php(286): SiteController->runAction()
#1 E:\Yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#2 E:\Yii\framework\web\CWebApplication.php(282): SiteController->run()
#3 E:\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 E:\Yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#5 E:\xampp\htdocs\Testapp\index.php(13): CWebApplication->run()
REQUEST_URI=/Testapp/index.php?r=Site/Reset
in E:\xampp\htdocs\Testapp\protected\controllers\SiteController.php (79)
in E:\xampp\htdocs\Testapp\index.php (13)
